# Generated by Django 5.2.7 on 2025-11-13 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App Notification'), ('push', 'Push Notification'), ('sms', 'SMS')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config_template', models.JSONField(default=dict, help_text='Configuración específica del canal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canal de Notificación',
                'verbose_name_plural': 'Canales de Notificación',
                'db_table': 'notifications_channel',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código único')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Asunto')),
                ('body', models.TextField(verbose_name='Cuerpo del mensaje')),
                ('body_html', models.TextField(blank=True, verbose_name='Cuerpo HTML (para email)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('context_variables', models.JSONField(default=list, help_text="Lista de variables disponibles. Ej: ['user_name', 'action_url']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channels', models.ManyToManyField(to='notifications.notificationchannel', verbose_name='Canales')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
                'db_table': 'notifications_template',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.JSONField(default=dict, help_text='Variables para reemplazar en la plantilla', verbose_name='Contexto')),
                ('status', models.CharField(choices=[('pending', '🔄 Pendiente'), ('sent', '✅ Enviada'), ('delivered', '📨 Entregada'), ('read', '👀 Leída'), ('failed', '❌ Fallida'), ('cancelled', '🚫 Cancelada')], default='pending', max_length=20, verbose_name='Estado')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Si está vacío, se envía inmediatamente', null=True, verbose_name='Programada para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada el')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('delivery_attempts', models.IntegerField(default=0, verbose_name='Intentos de envío')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Último intento')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('config', models.JSONField(default=dict, help_text='Configuración específica para este usuario/canal', verbose_name='Configuración')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel', verbose_name='Canal')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate', verbose_name='Plantilla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificación',
                'db_table': 'notifications_user_preference',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '🔄 Pendiente'), ('sent', '✅ Enviada'), ('delivered', '📨 Entregada'), ('read', '👀 Leída'), ('failed', '❌ Fallida'), ('cancelled', '🚫 Cancelada')], max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada el')),
                ('external_id', models.CharField(blank=True, help_text='ID del proveedor externo (email provider, push service, etc.)', max_length=255, verbose_name='ID Externo')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel', verbose_name='Canal')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification', verbose_name='Notificación')),
            ],
            options={
                'verbose_name': 'Entrega de Notificación',
                'verbose_name_plural': 'Entregas de Notificaciones',
                'db_table': 'notifications_delivery',
                'indexes': [models.Index(fields=['notification', 'channel'], name='notificatio_notific_0422e0_idx'), models.Index(fields=['sent_at'], name='notificatio_sent_at_6e9fa3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['code', 'is_active'], name='notificatio_code_e6d0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status', 'created_at'], name='notificatio_user_id_cd4f27_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_d8d933_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotificationpreference',
            index=models.Index(fields=['user', 'is_enabled'], name='notificatio_user_id_582902_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotificationpreference',
            unique_together={('user', 'template', 'channel')},
        ),
    ]
