# Generated by Django 5.2.7 on 2025-10-30 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_organization', '0001_initial'),
        ('core_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Departamento específico para este rol', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_organization.department'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='department_filter',
            field=models.ForeignKey(blank=True, help_text='Aplicar permiso solo a este departamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='core_organization.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
