# Generated by Django 5.2.7 on 2025-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_permissions', '0002_alter_userrole_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmodule',
            name='icon',
            field=models.CharField(blank=True, help_text='Icono para la UI', max_length=50, verbose_name='icon'),
        ),
    ]
