# Generated by Django 5.2.7 on 2025-11-15 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_permissions', '0003_alter_permissionmodule_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código único')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_default', models.BooleanField(default=False, verbose_name='Preset por defecto')),
                ('required_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_permissions.role', verbose_name='Rol requerido')),
            ],
            options={
                'verbose_name': 'Preset de Dashboard',
                'verbose_name_plural': 'Presets de Dashboard',
                'db_table': 'dashboard_preset',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código único')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('widget_type', models.CharField(choices=[('notifications_stats', 'Estadísticas de Notificaciones'), ('recent_activity', 'Actividad Reciente'), ('user_stats', 'Estadísticas de Usuario'), ('system_health', 'Salud del Sistema'), ('quick_actions', 'Acciones Rápidas'), ('recent_notifications', 'Notificaciones Recientes')], max_length=50, verbose_name='Tipo de Widget')),
                ('component_name', models.CharField(help_text='Nombre del componente Angular para este widget', max_length=255, verbose_name='Componente Angular')),
                ('data_endpoint', models.CharField(help_text='URL para obtener datos del widget', max_length=255, verbose_name='Endpoint de datos')),
                ('default_config', models.JSONField(default=dict, verbose_name='Configuración por defecto')),
                ('default_size', models.CharField(choices=[('small', 'Pequeño (1x1)'), ('medium', 'Mediano (2x1)'), ('large', 'Grande (2x2)'), ('xlarge', 'Extra Grande (3x2)')], default='medium', max_length=20, verbose_name='Tamaño por defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_permissions', models.ManyToManyField(blank=True, help_text='Permisos necesarios para ver este widget', to='core_permissions.granularpermission', verbose_name='Permisos requeridos')),
            ],
            options={
                'verbose_name': 'Widget de Dashboard',
                'verbose_name_plural': 'Widgets de Dashboard',
                'db_table': 'dashboard_widget',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PresetWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.JSONField(default=dict)),
                ('config', models.JSONField(default=dict)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardpreset')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardwidget')),
            ],
            options={
                'db_table': 'dashboard_preset_widget',
                'unique_together': {('preset', 'widget')},
            },
        ),
        migrations.AddField(
            model_name='dashboardpreset',
            name='widgets',
            field=models.ManyToManyField(through='dashboard.PresetWidget', to='dashboard.dashboardwidget', verbose_name='Widgets'),
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(default=dict, help_text='Configuración del layout en formato Gridster', verbose_name='Layout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dashboard de Usuario',
                'verbose_name_plural': 'Dashboards de Usuario',
                'db_table': 'dashboard_user_dashboard',
            },
        ),
        migrations.CreateModel(
            name='UserWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.JSONField(default=dict, help_text='Posición en el grid: {x, y, cols, rows}', verbose_name='Posición y tamaño')),
                ('config', models.JSONField(default=dict, help_text='Configuración personalizada para este widget', verbose_name='Configuración específica')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='Intervalo de actualización (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.userdashboard', verbose_name='Dashboard de usuario')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardwidget', verbose_name='Widget')),
            ],
            options={
                'verbose_name': 'Widget de Usuario',
                'verbose_name_plural': 'Widgets de Usuario',
                'db_table': 'dashboard_user_widget',
                'ordering': ['position'],
                'unique_together': {('user_dashboard', 'widget')},
            },
        ),
    ]
