# Generated by Django 5.2.7 on 2025-10-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
