# Generated by Django 5.2.7 on 2025-10-28 04:00

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='location name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='location code')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state/province')),
                ('country', models.CharField(default='El Salvador', max_length=100, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'db_table': 'core_organization_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='department name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='department code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='department email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='department phone')),
                ('budget_code', models.CharField(blank=True, max_length=50, verbose_name='budget code')),
                ('cost_center', models.CharField(blank=True, max_length=50, verbose_name='cost center')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='department manager')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core_organization.department', verbose_name='parent department')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='core_organization.location', verbose_name='location')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'db_table': 'core_organization_departments',
                'ordering': ['tree_id', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='job title')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='position code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('position_type', models.CharField(choices=[('executive', 'Executive'), ('management', 'Management'), ('professional', 'Professional'), ('technical', 'Technical'), ('administrative', 'Administrative'), ('support', 'Support'), ('intern', 'Intern')], default='professional', max_length=20, verbose_name='position type')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='job level')),
                ('salary_grade', models.CharField(blank=True, max_length=20, verbose_name='salary grade')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='minimum salary')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum salary')),
                ('requirements', models.TextField(blank=True, verbose_name='requirements')),
                ('responsibilities', models.TextField(blank=True, verbose_name='responsibilities')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_remote', models.BooleanField(default=False, verbose_name='remote position')),
                ('openings_count', models.PositiveIntegerField(default=1, verbose_name='number of openings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='core_organization.department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'job position',
                'verbose_name_plural': 'job positions',
                'db_table': 'core_organization_job_positions',
                'ordering': ['department', 'level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='schedule name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='schedule code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='break start')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='break end')),
                ('monday', models.BooleanField(default=True, verbose_name='Monday')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Tuesday')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Wednesday')),
                ('thursday', models.BooleanField(default=True, verbose_name='Thursday')),
                ('friday', models.BooleanField(default=True, verbose_name='Friday')),
                ('saturday', models.BooleanField(default=False, verbose_name='Saturday')),
                ('sunday', models.BooleanField(default=False, verbose_name='Sunday')),
                ('is_flexible', models.BooleanField(default=False, verbose_name='flexible schedule')),
                ('core_hours_start', models.TimeField(blank=True, null=True, verbose_name='core hours start')),
                ('core_hours_end', models.TimeField(blank=True, null=True, verbose_name='core hours end')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('departments', models.ManyToManyField(blank=True, related_name='work_schedules', to='core_organization.department', verbose_name='departments')),
                ('job_positions', models.ManyToManyField(blank=True, related_name='work_schedules', to='core_organization.jobposition', verbose_name='job positions')),
            ],
            options={
                'verbose_name': 'work schedule',
                'verbose_name_plural': 'work schedules',
                'db_table': 'core_organization_work_schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='employee ID')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='hire date')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='termination date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core_organization.department', verbose_name='department')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core_organization.jobposition', verbose_name='job position')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='supervisor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizational_assignment', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('work_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core_organization.workschedule', verbose_name='work schedule')),
            ],
            options={
                'verbose_name': 'organizational assignment',
                'verbose_name_plural': 'organizational assignments',
                'db_table': 'core_organization_assignments',
                'ordering': ['department', 'job_position'],
            },
        ),
    ]
