# Generated by Django 5.2.7 on 2025-11-03 01:53

import core_audit.models
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('audit_log_retention_days', models.IntegerField(choices=[(30, '30 days'), (90, '90 days'), (180, '180 days'), (365, '1 year'), (730, '2 years'), (1825, '5 years'), (0, 'Indefinitely')], default=365, verbose_name='audit log retention days')),
                ('security_event_retention_days', models.IntegerField(choices=[(30, '30 days'), (90, '90 days'), (180, '180 days'), (365, '1 year'), (730, '2 years'), (1825, '5 years'), (0, 'Indefinitely')], default=730, verbose_name='security event retention days')),
                ('system_change_retention_days', models.IntegerField(choices=[(30, '30 days'), (90, '90 days'), (180, '180 days'), (365, '1 year'), (730, '2 years'), (1825, '5 years'), (0, 'Indefinitely')], default=1825, verbose_name='system change retention days')),
                ('enable_login_auditing', models.BooleanField(default=True, verbose_name='enable login auditing')),
                ('enable_data_access_auditing', models.BooleanField(default=True, verbose_name='enable data access auditing')),
                ('enable_permission_changes_auditing', models.BooleanField(default=True, verbose_name='enable permission changes auditing')),
                ('enable_api_auditing', models.BooleanField(default=True, verbose_name='enable API auditing')),
                ('enable_business_process_auditing', models.BooleanField(default=True, verbose_name='enable business process auditing')),
                ('enable_security_alerts', models.BooleanField(default=True, verbose_name='enable security alerts')),
                ('failed_login_threshold', models.PositiveIntegerField(default=5, verbose_name='failed login threshold')),
                ('failed_login_timeframe_minutes', models.PositiveIntegerField(default=30, verbose_name='failed login timeframe (minutes)')),
                ('alert_email_recipients', models.TextField(blank=True, help_text='Comma-separated list of email addresses', verbose_name='alert email recipients')),
                ('enable_auto_archiving', models.BooleanField(default=True, verbose_name='enable auto archiving')),
                ('archive_after_days', models.PositiveIntegerField(default=90, verbose_name='archive after days')),
                ('enable_compression', models.BooleanField(default=True, verbose_name='enable compression')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'audit configuration',
                'verbose_name_plural': 'audit configurations',
                'db_table': 'core_audit_configurations',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ID para correlacionar eventos relacionados', verbose_name='correlation ID')),
                ('action_category', models.CharField(choices=[('authentication', 'Authentication'), ('user_management', 'User Management'), ('permission_management', 'Permission Management'), ('data_access', 'Data Access'), ('data_modification', 'Data Modification'), ('system_config', 'System Configuration'), ('security', 'Security'), ('business', 'Business Process'), ('api', 'API Access')], db_index=True, max_length=50, verbose_name='action category')),
                ('action_type', models.CharField(choices=[('login_success', 'Login Successful'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('session_timeout', 'Session Timeout'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('2fa_verified', '2FA Verified'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_activated', 'User Activated'), ('user_deactivated', 'User Deactivated'), ('profile_updated', 'Profile Updated'), ('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_deleted', 'Role Deleted'), ('permission_assigned', 'Permission Assigned'), ('permission_revoked', 'Permission Revoked'), ('user_role_assigned', 'User Role Assigned'), ('user_role_removed', 'User Role Removed'), ('permission_escalation', 'Permission Escalation'), ('data_viewed', 'Data Viewed'), ('data_exported', 'Data Exported'), ('data_imported', 'Data Imported'), ('sensitive_data_accessed', 'Sensitive Data Accessed'), ('bulk_data_accessed', 'Bulk Data Accessed'), ('record_created', 'Record Created'), ('record_updated', 'Record Updated'), ('record_deleted', 'Record Deleted'), ('bulk_update', 'Bulk Update'), ('bulk_delete', 'Bulk Delete'), ('config_changed', 'Configuration Changed'), ('system_backup', 'System Backup'), ('system_restore', 'System Restore'), ('maintenance_mode', 'Maintenance Mode'), ('api_call', 'API Call'), ('api_rate_limit', 'API Rate Limit Exceeded'), ('api_authentication_failed', 'API Authentication Failed')], db_index=True, max_length=50, verbose_name='action type')),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=20, verbose_name='severity level')),
                ('description', models.TextField(verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('old_values', core_audit.models.CustomJSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='old values')),
                ('new_values', core_audit.models.CustomJSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='new values')),
                ('changed_fields', core_audit.models.CustomJSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='changed fields')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='request path')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='request method')),
                ('is_success', models.BooleanField(db_index=True, default=True, verbose_name='successful')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('stack_trace', models.TextField(blank=True, verbose_name='stack trace')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='session key')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration milliseconds')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='archived')),
                ('archive_date', models.DateTimeField(blank=True, null=True, verbose_name='archive date')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('user_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_organization.department', verbose_name='user department')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'db_table': 'core_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='event ID')),
                ('event_type', models.CharField(choices=[('multiple_failed_logins', 'Multiple Failed Logins'), ('suspicious_activity', 'Suspicious Activity'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('data_breach_attempt', 'Data Breach Attempt'), ('privilege_escalation', 'Privilege Escalation Attempt'), ('malicious_activity', 'Malicious Activity Detected'), ('brute_force_attempt', 'Brute Force Attempt'), ('anomalous_behavior', 'Anomalous User Behavior'), ('data_exfiltration', 'Data Exfiltration Attempt'), ('account_takeover', 'Account Takeover Attempt')], db_index=True, max_length=50, verbose_name='event type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20, verbose_name='severity level')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20, verbose_name='priority')),
                ('evidence_data', core_audit.models.CustomJSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='evidence data')),
                ('ip_addresses', core_audit.models.CustomJSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='IP addresses')),
                ('user_agents', core_audit.models.CustomJSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='user agents')),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('investigating', 'Under Investigation'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('false_positive', 'False Positive'), ('closed', 'Closed')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('investigation_notes', core_audit.models.CustomJSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='investigation notes')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('resolution_code', models.CharField(blank=True, choices=[('benign', 'Benign Activity'), ('malicious', 'Malicious Activity'), ('misconfiguration', 'System Misconfiguration'), ('user_error', 'User Error'), ('other', 'Other')], max_length=50, verbose_name='resolution code')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='detected at')),
                ('first_occurrence', models.DateTimeField(blank=True, null=True, verbose_name='first occurrence')),
                ('last_occurrence', models.DateTimeField(blank=True, null=True, verbose_name='last occurrence')),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='resolved at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('occurrence_count', models.PositiveIntegerField(default=1, verbose_name='occurrence count')),
                ('is_auto_resolved', models.BooleanField(default=False, verbose_name='auto resolved')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_events', to=settings.AUTH_USER_MODEL)),
                ('related_audit_logs', models.ManyToManyField(blank=True, related_name='security_events', to='core_audit.auditlog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
                ('user_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_organization.department', verbose_name='user department')),
            ],
            options={
                'verbose_name': 'security event',
                'verbose_name_plural': 'security events',
                'db_table': 'core_security_events',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('change_type', models.CharField(choices=[('user_permissions', 'User Permissions'), ('role_config', 'Role Configuration'), ('system_settings', 'System Settings'), ('security_policies', 'Security Policies'), ('business_rules', 'Business Rules'), ('audit_config', 'Audit Configuration'), ('notification_config', 'Notification Configuration')], db_index=True, max_length=50, verbose_name='change type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('old_configuration', core_audit.models.CustomJSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='old configuration')),
                ('new_configuration', core_audit.models.CustomJSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='new configuration')),
                ('change_summary', models.TextField(blank=True, verbose_name='change summary')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='requires approval')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('approval_notes', models.TextField(blank=True, verbose_name='approval notes')),
                ('can_be_reverted', models.BooleanField(default=True, verbose_name='can be reverted')),
                ('is_reverted', models.BooleanField(default=False, verbose_name='is reverted')),
                ('reverted_at', models.DateTimeField(blank=True, null=True, verbose_name='reverted at')),
                ('revert_reason', models.TextField(blank=True, verbose_name='revert reason')),
                ('impact_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='impact level')),
                ('affected_users', models.PositiveIntegerField(default=0, verbose_name='affected users')),
                ('rollback_plan', models.TextField(blank=True, verbose_name='rollback plan')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='changed at')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='scheduled for')),
                ('is_emergency_change', models.BooleanField(default=False, verbose_name='emergency change')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_changes', to=settings.AUTH_USER_MODEL)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'system change',
                'verbose_name_plural': 'system changes',
                'db_table': 'core_system_changes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp', 'action_category'], name='core_audit__timesta_f7c4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='core_audit__user_id_607f52_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'is_success'], name='core_audit__action__e8b032_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='core_audit__ip_addr_8b4aae_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id', 'timestamp'], name='core_audit__content_803159_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['correlation_id'], name='core_audit__correla_f88b04_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'status'], name='core_securi_event_t_0dc34d_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity', 'priority'], name='core_securi_severit_cb7220_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['detected_at', 'resolved_at'], name='core_securi_detecte_a98d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['assigned_to', 'status'], name='core_securi_assigne_c647c4_idx'),
        ),
        migrations.AddIndex(
            model_name='systemchange',
            index=models.Index(fields=['change_type', 'changed_at'], name='core_system_change__f467c4_idx'),
        ),
        migrations.AddIndex(
            model_name='systemchange',
            index=models.Index(fields=['changed_by', 'changed_at'], name='core_system_changed_d0f6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='systemchange',
            index=models.Index(fields=['requires_approval', 'approved_at'], name='core_system_require_872d88_idx'),
        ),
    ]
